apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: aishjp/auth-service:latest
          ports:
            - containerPort: 8082
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
