apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: default
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:8.12.0
        args: ["-f", "/usr/share/logstash/pipeline/logstash.conf"]
        ports:
        - containerPort: 5044
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/logstash/pipeline/logstash.conf
          subPath: logstash.conf
          readOnly: true
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: config-volume
        configMap:
          name: logstash-config
          # Optional: you can specify items explicitly, but here whole configmap is fine
          # items:
          # - key: logstash.conf
          #   path: logstash.conf
