apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: default
spec:
  selector:
    app: logstash
  ports:
    - port: 5044
      targetPort: 5044
      protocol: TCP
  type: ClusterIP
