- name: Create Kubernetes deployment manifest
  template:
    src: deployment.yaml.j2
    dest: ../../k8s/auth-deployment.yaml

- name: Create Kubernetes service manifest
  template:
    src: service.yaml.j2
    dest: ../../k8s/auth-service.yaml

- name: Apply Kubernetes deployment
  shell: kubectl apply -f ../../k8s/auth-deployment.yaml

- name: Apply Kubernetes service
  shell: kubectl apply -f ../../k8s/auth-service.yaml

- name: Create Kubernetes HPA manifest
  template:
    src: auth-hpa.yaml.j2
    dest: ../../k8s/auth-hpa.yaml

- name: Apply Kubernetes HPA
  shell: kubectl apply -f ../../k8s/auth-hpa.yaml
